const routes = {
    home: '/',
    menu: '/menu',
    table: '/table',
    introduce: '/introduce',
    contact: '/contact',
    login: '/login',
    member: '/member',
    booktable: '/booktable',
    list: '/list',
    room: '/room',
    sale: '/sales',
    search: '/search',
    register: '/register',
    dashboard: '/admin/dashboard',
    adlogin: '/admin/login',
    managerbooking: '/admin/managerbooking',
    manageuser: '/admin/manageuser',
    staff: '/admin/staff',
    reviews: '/admin/reviews',
    booking: '/booking',
    //homeadmin:'/admin/home',
};

export default routes;
